service: ddns
provider:
  name: aws
  runtime: rust
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  tags:
    app: ddns
  environment:
    USERS_TABLE_NAME: ${self:custom.tableName}
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - 'Fn::Join':
          - ':'
          - - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/${self:custom.tableName}'
    - Effect: Allow
      Action:
        - route53:ChangeResourceRecordSets
      Resource:
        - arn:aws:route53:::hostedzone/*
    - Effect: Allow
      Action:
        - route53:ListHostedZones
      Resource:
        - "*"
  apiKeys:
    - ${opt:stage, 'dev'}-adminKey
  

custom:
  rust:
    dockerless: true
  tableName: ${self:service}-${opt:stage, 'dev'}-UsersTable

package:
  individually: true

plugins:
  - serverless-rust
functions:
  create_user:
    handler: create_user
    description: Creates an authorized user to update DNS record
    events:
      - http:
          path: user
          method: post
          private: true # Requires clients to add API keys values in the `x-api-key` header of their request
          request:
            headers:
              Content-Type: true
            schema:
              application/json: ${file(requests/create_user.json)}

  nic:
    handler: nic
    description: Update DNS records
    events:
      - http:
          path: nic/update
          method: get
          request:
            headers:
              User-Agent: true
              Authorization: true
            querystrings:
              hostname: true
              myip: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: app
            Value: ddns
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
